### ISSUE TITLE
publish crate

### ISSUE THREAD

**Issue by 89z** [alexgibson/rust-parse-url#2]
it seems crate is using name `parse_url`:

https://github.com/alexgibson/rust-parse-url/blob/a4cd9c1abdbba80c173ebab6efd376ea65373c68/Cargo.toml#L2

but another published crate is already using that name:

<https://crates.io/crates/parse_url>

**Comment by alexgibson** [comment]
I have no interest in publishing this crate, thank you

**Comment by 89z** [comment]
Looks like you can do it like this:

~~~toml
[dependencies]
parse_url = { git = "https://github.com/alexgibson/rust-parse-url" }
~~~

it wouldn't hurt to add that to the Readme
